# THIS FILE IS AUTOMATICALLY GENERATED.
# Disclaimer: Please test this file before using in production.
"""
Generated blueprint DSL (.py)
"""

import json  # no_qa
import os  # no_qa

from calm.dsl.builtins import *  # no_qa


# Secret Variables
BP_CRED_AWSKEY_KEY = read_local_file("BP_CRED_AWSKEY_KEY")

# Credentials
BP_CRED_AWSKEY = basic_cred(
    "ubuntu",
    BP_CRED_AWSKEY_KEY,
    name="AWSKEY",
    type="KEY",
    default=True,
)


class Service1(Service):

    pass


class VM1(Substrate):

    os_type = "Linux"
    provider_type = "AWS_VM"
    provider_spec = read_provider_spec(os.path.join("specs", "VM1_provider_spec.yaml"))

    readiness_probe = readiness_probe(
        connection_type="SSH",
        disabled=False,
        retries="5",
        connection_port=22,
        address="@@{public_ip_address}@@",
        delay_secs="60",
        credential=ref(BP_CRED_AWSKEY),
    )


class Package1(Package):

    services = [ref(Service1)]

    @action
    def __install__():

        CalmTask.Exec.ssh(
            name="update",
            filename=os.path.join(
                "scripts", "Package_Package1_Action___install___Task_update.sh"
            ),
            cred=ref(BP_CRED_AWSKEY),
            target=ref(Service1),
        )


class ef119a52_deployment(Deployment):

    min_replicas = "1"
    max_replicas = "1"
    default_replicas = "1"

    packages = [ref(Package1)]
    substrate = ref(VM1)


class Default(Profile):

    deployments = [ef119a52_deployment]


class aws_test(Blueprint):

    services = [Service1]
    packages = [Package1]
    substrates = [VM1]
    profiles = [Default]
    credentials = [BP_CRED_AWSKEY]
